// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcopgknrpjenixejhlfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjb3Bna25ycGplbml4ZWpobGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDY2MTgsImV4cCI6MjA2NDIyMjYxOH0.eBOejieDJaIwD89FZPJYDzr4Vx9f8ad6KxSFDbO85bI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);